language: python
python:
  - "2.7"
env:
  - DJANGO=1.7
  - DJANGO=1.8
install:
  - pip install Django==$DJANGO
  - pip install flake8
  - pip install -r requirements.txt
script:
  - python manage.py test