language: python
python:
  - "2.7"
env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
install:
  - pip install Django==$DJANGO
  - pip install flake8
  - pip install -r SACHI-PDB/requirements.txt
script:
  - flake8 mainsite
  - python manage.py test